### ISSUE TITLE
JSON could not be parsed

### ISSUE THREAD

**Issue by vadi2** [cloudflare/har-sanitizer#14]
I exported a .har file from Firefox 118.0.2, and while the file was correctly analysed for metadata, downloading it fails with:

> SyntaxError: JSON.parse: expected ',' or ']' after array element at line 274 column 24 of the JSON data

The input har is json-valid, so something goes wrong during the transformation. What could be wrong? Ironically I can't provide it here due to sensitive information.

**Comment by BrijeshPateluh** [comment]
Hello James, 

I am seeing the same issue on the live URL. The input seems valid as other applications are able to parse the file. Just wanted to post here.

Thank you for the effort!

**Comment by 0x767676** [comment]
Hi, just tested with a HAR from a Cloudflare Access app, via latest Edge.

SyntaxError: Expected ',' or ']' after array element in JSON at position 553257 (line 1971 column 9)

HAR's valid. Lmk and I'll provide it :)

**Comment by DavidAccola** [comment]
+1 to this issue.

-Saved out a .har in Chrome after searching the word “test” on [google.com](http://google.com/)
-Uploaded to har-sanitizer.pages.dev
-Marked sanitization for “All Cookies”
-Selected Download Sanitized HAR
-Got error: “SyntaxError: Expected ‘,’ or ‘]’ after array element in JSON at position 13241 (line 236 column 9)”

![2024-06-11_10-18-56](https://github.com/cloudflare/har-sanitizer/assets/62493194/f0d64506-68af-4e70-8271-73911894e33c)
