### ISSUE TITLE
Send scrub options in curl

### ISSUE THREAD

**Issue by QAInsights** [cloudflare/har-sanitizer#16]
How can we include scrub options when using curl? I do not see any network calls when I customize the options.

**Comment by jroyal** [comment]
These are the options available in the scrub function when using curl. You just need to include them in the body that you send the HAR file in.

```ts
type ScrubRequest = {
	har: string;
	words?: string[];
	mime_types?: string[];
	all_headers?: boolean;
	all_cookies?: boolean;
	all_mimetypes?: boolean;
	all_queryargs?: boolean;
};
```

Using my example from the README you can do something like this 
```
jq '{"har": ., "all_headers": true, "words": ["my-auth-header"]}' < /Users/jroyal/Downloads/test_har_sanitizer.har  | curl -X POST -H "Content-Type: application/json" --data @- localhost:3001/scrub > scrubbed.har
```
