### ISSUE TITLE
Sensitive Info get stored anywhere

### ISSUE THREAD

**Issue by nryork** [cloudflare/har-sanitizer#23]
Hi!
I was wondering when putting sensitive info into this har-sanitizer, where does the PII info get stored, if it does?

**Comment by jroyal** [comment]
We don't store anything. The UI itself is all client side. If you happen to use the scrub endpoint then we just process the HAR and immediately return the sanitized har file. You can see what it does here https://github.com/cloudflare/har-sanitizer/blob/main/functions/scrub.tsx.

**Comment by nryork** [comment]
> We don't store anything. The UI itself is all client side. If you happen to use the scrub endpoint then we just process the HAR and immediately return the sanitized har file. You can see what it does here https://github.com/cloudflare/har-sanitizer/blob/main/functions/scrub.tsx.

Awesome! Thank you so much for that info
